person:
    pattern:  /
    defaults: { _controller: "HopeChurchGreaterBundle:Person:index" }

person_show:
    pattern:  /{id}/show
    defaults: { _controller: "HopeChurchGreaterBundle:Person:show" }

person_new:
    pattern:  /new
    defaults: { _controller: "HopeChurchGreaterBundle:Person:new" }

person_create:
    pattern:  /create
    defaults: { _controller: "HopeChurchGreaterBundle:Person:create" }
    requirements: { _method: post }

person_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "HopeChurchGreaterBundle:Person:edit" }

person_update:
    pattern:  /{id}/update
    defaults: { _controller: "HopeChurchGreaterBundle:Person:update" }
    requirements: { _method: post|put }

person_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HopeChurchGreaterBundle:Person:delete" }
    requirements: { _method: post|delete }
