hope_church_backend:
  path: /{action}/{type}

hope_church_greater:
  path:  /{page}.{_format}
  defaults: 
    _controller: HopeChurchGreaterBundle:Default:index
    page: home
    _format: html
  requirements:
    _format: html