########## Front-end Routes ##########

hope_church_greater_add_person:
  path: /add/person
  defaults:
    _controller: HopeChurchGreaterBundle:Default:addPerson

hope_church_greater:
  path:  /{page}.{_format}
  defaults: 
    _controller: HopeChurchGreaterBundle:Default:index
    page: home
    _format: html
  requirements:
    _format: html

########## Back-end Routes ##########

#--------- Attendees Page Routes ---------#
hope_church_backstage_get_attendees:
  path: /backstage/get/attendees/{event}/{date}
  defaults:
    _controller: HopeChurchGreaterBundle:Backstage:getAttendees
    event: 1 # sunday gathering
    date: 0 # no date

hope_church_backstage_update_attendees:
  path: /backstage/update/attendees
  defaults:
    _controller: HopeChurchGreaterBundle:Backstage:updateAttendees

#---------- Add-Person Page Routes ----------#

hope_church_backstage_update_person:
  path: /backstage/update/person
  defaults:
    _controller: HopeChurchGreaterBundle:Backstage:updatePerson

# this is the generic get route, it must be last
hope_church_backstage_get_generic:
  path: /backstage/get/{type}/{record_id}
  defaults:
    _controller: HopeChurchGreaterBundle:Backstage:get
    # the type of objects that can be retrieved
    type: people