HopeChurch\GreaterBundle\Entity\Person:
  properties:
    nameFirst:
      - NotBlank:
          message: "A first name must be given"
    age:
      - NotBlank:
          message: "An age group must be chosen"
#    roles:
#      - Count:
#          min: 0
#          minMessage: "At least one role must be specified"
