HopeChurch\GreaterBundle\Entity\Person:
  properties:
    nameFirst:
      - NotBlank:
          message: "A first name must be given"
    roles:
      - Count:
          min: 1
          minMessage: "At least one role must be specified"
