<?php

namespace TheCommons\SermonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SermonSeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SermonSeriesRepository extends EntityRepository
{
}
