the_commons_common_folk:
    resource: "@TheCommonsCommonFolkBundle/Resources/config/routing.yml"
    prefix:   /commonfolk/

the_commons_security:
    resource: "@TheCommonsSecurityBundle/Resources/config/routing.yml"
    prefix:   /

the_commons_homepage:
    resource: "@TheCommonsHomepageBundle/Resources/config/routing.yml"
    prefix:   /
