jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern:    ^/(login$|resetting)
            anonymous:  ~

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                provider:      fos_userbundle
                csrf_provider: form.csrf_provider
                use_referer:   true
            logout: true
            remember_me:
                key:      "gqqfcygtrgmvkbynridqesfhrcgcyyggdxv5gyfpjyfravqc"
                lifetime: 604800 # 7 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            switch_user: true

    access_control:
        - path: ^/login$
          role: IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/resetting
          role: IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/admin/
          roles: ROLE_ADMIN
        - path: ^/commonfolk
          roles: ROLE_USER
        - path: ^/
          roles: IS_AUTHENTICATED_ANONYMOUSLY