parameters:
#    hope_church_greater.example.class: TheCommons\CommonFolkBundle\Example

services:
  hope_church_greater.menu_builder:
    class: TheCommons\CommonFolkBundle\Menu\Builder
    arguments: ['@knp_menu.factory', '@security.authorization_checker']

  hope_church_greater.menu.topNav:
    class: Knp\Menu\MenuItem
    factory_service: hope_church_greater.menu_builder
    factory_method: topNavMenu
    tags:
      - { name: knp_menu.menu, alias: topNav }

#services:
#    hope_church_greater.example:
#        class: %hope_church_greater.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
