parameters:

services:
  the_commons_common_folk.menu_builder:
    class: TheCommons\CommonFolkBundle\Menu\Builder
    arguments: ['@knp_menu.factory', '@security.authorization_checker']

  the_commons_common_folk.menu.topNav:
    class: Knp\Menu\MenuItem
    factory_service: the_commons_common_folk.menu_builder
    factory_method: topNavMenu
    tags:
      - { name: knp_menu.menu, alias: topNav }
