<?php

namespace TheCommons\CommonFolkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgeRepository extends EntityRepository
{
}
