<?php

namespace TheCommons\CommonFolkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiscipleshipStageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscipleshipStageRepository extends EntityRepository
{

  public function findMentors($dstage_id)
  {
    return $this->createQueryBuilder('t')
      ->select(array('trp.id', 'trp.nameFirst', 'trp.nameLast'))
      ->innerJoin('t.mentorRoles', 'troles')
      ->innerJoin('troles.people', 'trp')
      ->where('t.id = :dstage_id')
      ->addOrderBy('trp.nameFirst', 'ASC')
      ->addOrderBy('trp.nameLast', 'ASC')
      ->setParameter('dstage_id', $dstage_id)
      ->getQuery()
      ->getResult();
  }

}
