########## Entity Routes ##########
HopeChurchGreaterBundle_person:
        resource: "@HopeChurchGreaterBundle/Resources/config/routing/person.yml"
        prefix:   /person

########## Front-end Routes ##########
# This default route MUST come last  #
hope_church_greater:
  path:  /{page}/{subpage}
  defaults:
    _controller: HopeChurchGreaterBundle:Default:index
    page: home
    subpage:

########## Back-end Routes ##########
# TODO: Refactor this into a BackendBundle

#---------- Overall Attendees Page Routes ----------#
hope_church_backstage_get_overall_attendees:
  path: /backstage/get/attendees/overall/{event}/{date}
  defaults:
    _controller: HopeChurchGreaterBundle:Backstage:getOverallAttendees
    event: 1 #sunday gathering
    date: 0 # no date

hope_church_backstage_update_overall_attendees:
  path: /backstage/update/attendees/overall/
  defaults:
    _controller: HopeChurchGreaterBundle:Backstage:updateOverallAttendees

#--------- Attendees Page Routes ---------#
hope_church_backstage_get_attendees:
  path: /backstage/get/attendees/{event}/{role}/{date}
  defaults:
    _controller: HopeChurchGreaterBundle:Backstage:getAttendees
    event: 1 # sunday gathering
    role: all
    date: 0 # no date

hope_church_backstage_update_attendees:
  path: /backstage/update/attendees/{event}/{date}
  defaults:
    _controller: HopeChurchGreaterBundle:Backstage:updateAttendees
    event: 1 # sunday gathering
    date: 0 # no date

#---------- Mentor Page Routes ----------#
hope_church_backstage_get_mentor_by_dstage:
  path: /backstage/get/mentors/{dstage}
  defaults:
    _controller: HopeChurchGreaterBundle:Backstage:getMentorByDiscipleshipStage
    dstage: 0