the_commons_sermon_sermon:
    resource: "@TheCommonsSermonBundle/Resources/config/routing/sermon.yml"
    prefix:   /sermons

the_commons_sermon_series:
    resource: "@TheCommonsSermonBundle/Resources/config/routing/sermonseries.yml"
    prefix:   /series

the_commons_sermon:
    path:     /{format}
    defaults:
        _controller: TheCommonsSermonBundle:Default:get
        format: xml
    requirements:
        format: xml|json
